### ISSUE TITLE
Abstract Carousel Logic

### ISSUE THREAD

**Issue by mmwtsn** [DoSomething/neue#147]
There is a image slideshow (carousel) in the Action Page's "Prove It" section. Right now the markup is hard-coded into the campaign template. It would be swell if that was generated automatically by the pattern library.

Suggested functionality:
  1. Developer applies `js-carousel` class to wrapping container
  2. `prev` and `next` buttons are automatically created and added to the DOM
  3. Additional id and classes applied to the images as necessary

**Comment by DFurnes** [comment]
Carousel pattern is being removed since it won't be used after Reportback 2.0 fully launches. Closing!
