### ISSUE TITLE
Underline links in dropdowns

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/neue#457]
It can be hard to tell what link you're hovering on in the dropdown. Can we add the underline we use on tertiary links to add a bit of clarity?

![screen shot 2015-02-17 at 12 47 54 pm](https://cloud.githubusercontent.com/assets/1865372/6233757/3a21f7bc-b6a3-11e4-9055-40bf1b04e327.png)

cc: @deadlybutter

**Comment by deadlybutter** [comment]
need me to work on this?

**Comment by DFurnes** [comment]
Yes please! :art:

**Comment by deadlybutter** [comment]
hmm, shouldnt this be an issue at dosomething? All I need to do is add the -tertiary class to the list elements

**Comment by DFurnes** [comment]
Works for me.

**Comment by deadlybutter** [comment]
apparently that doesn't work.... time to add it in neue!  ( @DFurnes can you reopen this? I haz no perms)

**Comment by DFurnes** [comment]
:dancer:
