### ISSUE TITLE
Extra quotation mark in url-encode sass function

### ISSUE THREAD

**Issue by weerd** [DoSomething/neue#465]
![image](https://cloud.githubusercontent.com/assets/105849/6428432/768e1954-bf6f-11e4-91da-2ccf79146fbf.png)

Not sure if this is an error or not, but syntax highlighting was all messed up. I presume it's an error and not an escaping thing?

**Comment by DFurnes** [comment]
Escaping! Not sure why it's messing up syntax highlighting. `%22` is the escaped code for `"`, but since our code style says to use double-quotes, I'm using the escaped version.
